attemptDeadline: 180s
httpTarget:
  headers:
    User-Agent: Google-Cloud-Scheduler
  httpMethod: POST
  uri: https://us-central1-second-brain-482901.cloudfunctions.net/dailyGithubScreenshot
lastAttemptTime: '2026-01-29T04:59:24.321518Z'
name: projects/second-brain-482901/locations/us-central1/jobs/daily-github-screenshot-updater
retryConfig:
  maxBackoffDuration: 3600s
  maxDoublings: 5
  maxRetryDuration: 0s
  minBackoffDuration: 5s
schedule: 59 23 * * *
scheduleTime: '2026-01-30T04:59:04.519309Z'
state: ENABLED
status: {}
timeZone: America/New_York
userUpdateTime: '2026-01-06T18:52:25.621120Z'
