attemptDeadline: 180s
httpTarget:
  headers:
    User-Agent: Google-Cloud-Scheduler
  httpMethod: GET
  uri: https://us-central1-second-brain-482901.cloudfunctions.net/rocketbook-fetch
lastAttemptTime: '2026-01-29T06:00:24.402721Z'
name: projects/second-brain-482901/locations/us-central1/jobs/rocketbook-daily-fetch
retryConfig:
  maxBackoffDuration: 3600s
  maxDoublings: 5
  maxRetryDuration: 0s
  minBackoffDuration: 5s
schedule: 0 0 * * *
scheduleTime: '2026-01-30T06:00:03.300393Z'
state: ENABLED
status: {}
timeZone: America/Mexico_City
userUpdateTime: '2025-12-31T05:24:17.338048Z'
